### PR TITLE
fix: options behaviour in `findAPortNotInUse` and `findAPortInUse`

### PR DESCRIPTION
**Pull request by evilebottnawi**
@laggingreflex 
Include:
1. Fix options behaviour in `findAPortNotInUse` and `findAPortInUse`
2. Improve tests and increase coverage (`99.07%`)
3. Update `async` to latest (import perf)

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@laggingreflex also i can rewrite tests using jest (in next PR), it is allow mocking and do tests more simple and stable

**Comment by laggingreflex** [comment]
Hi @evilebottnawi Extremely sorry for delay. 

>1. Fix options behaviour in `findAPortNotInUse` and `findAPortInUse`

I don't see `findAPortNotInUse` or `findAPortInUse` functions ever accepting an `options` argument. Only the `checkPortStatus` function does so. Although `findAPortNotInUse` doesn't throw when passed `options` it doesn't work either. 

[You said that it's being used this way in browser-sync][1], I'm not sure why they used it that way. 

This could be a great feature, but I just wanna be clear on whether this is fixing a bug which is causing other projects dependent on it fail, or it's just a new feature? 

----

Another thing was that I couldn't run tests. Got an error:

```
  √ checkPortStatus - free (with host in options argument) (401ms)
C:\...\portscanner\test.js:191
      t.is(t._expr(t._capt(t._capt(error, 'arguments/0/object').code, 'arguments/0'), {
                                                               ^

TypeError: Cannot read property 'code' of null
    at C:\...\portscanner\test.js:191:64
    at Socket.<anonymous> (C:\...\portscanner\lib\portscanner.js:132:5)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at TCP._handle.close [as _onclose] (net.js:558:12)
  √ checkPortStatus - free (402ms)
TypeError: Cannot read property 'stack' of undefined
    at error (C:\...\portscanner\node_modules\ava\cli.js:51:20)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.<anonymous> (C:\...\portscanner\node_modules\ava\cli.js:216:34)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    ...
```

I hope this isn't just my OS (Windows). I've [set up CircleCI][3].

---

I'm in favour of Jest. 

---

Lastly, I wanna [set up something like don't-break][2] before adding any new features so please give me some time for that as well. 

[1]: https://github.com/baalexander/node-portscanner/issues/25#issuecomment-348130116
[2]: https://github.com/baalexander/node-portscanner/issues/58
[3]: https://github.com/baalexander/node-portscanner/issues/57
[4]: https://github.com/BrowserSync/browser-sync/commit/9dc5d65fceb53edb318eb4c3e120d4062738b48f

**Comment by laggingreflex** [comment]
I tested it on *nix and the tests are passing. I also tested against browser-sync whose tests are passing too. So this should be good to release.

Sorry about the delay again.

**Comment by laggingreflex** [comment]
Merged, `2.2.0` released.

**Pull request merged**
